# Generated by Django 3.1.6 on 2021-03-02 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Arucikk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nev', models.CharField(max_length=128)),
                ('db', models.CharField(max_length=128)),
            ],
            options={
                'verbose_name': 'Áru',
                'verbose_name_plural': 'Áruk',
            },
        ),
    ]
