# Generated by Django 3.1.6 on 2021-03-04 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elsoapp', '0002_auto_20210304_2107'),
    ]

    operations = [
        migrations.AddField(
            model_name='arucikk',
            name='mertekegyseg',
            field=models.CharField(default='SOME STRING', max_length=128),
        ),
    ]
