# Generated by Django 3.1.6 on 2021-03-04 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elsoapp', '0003_arucikk_mertekegyseg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arucikk',
            name='mertekegyseg',
            field=models.CharField(default='', max_length=128),
        ),
    ]
