# Generated by Django 3.1.6 on 2021-03-08 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elsoapp', '0004_auto_20210304_2113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arucikk',
            name='db',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='arucikk',
            name='nev',
            field=models.CharField(default='', max_length=128),
        ),
    ]
